version: '2.4'
services:
  postgres:
    image: postgres
    container_name: ogl
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DATABASE=test
    command: postgres
    restart: always

